// Feature: browser-admin-editor, Property 1: JS-literal round-trip
//
// For any JavaScript source file the extractor accepts and any value `v`
// equal to the parsed content of the named literal inside that file, the
// writer SHALL produce a file byte-for-byte identical to the input outside
// [literalStart, literalEnd), and re-reading the rewritten file SHALL yield
// a value deeply equal to `v`.
//
// Validates: Requirement 3.2, 4.4

import { test } from 'node:test';
import { assert, forAll, pick, range, genAsciiString } from './harness.mjs';
import { loadModule } from '../assets/js/admin-editor-test-shim.js';

const jsl = await loadModule('admin-editor-js-literal');

// ── Generators ─────────────────────────────────────────────────────────

function genSafeString() {
  // Strings that round-trip safely through our emitter (no backticks, since
  // the emitter uses single or double quotes and never templates).
  const s = genAsciiString(0, 30).replace(/[`]/g, '');
  return s;
}

function genScalar() {
  const kind = pick(['string', 'number', 'bool', 'null']);
  if (kind === 'string') return genSafeString();
  if (kind === 'number') return pick([0, 1, -1, 3.14, -42, 1000]);
  if (kind === 'bool') return pick([true, false]);
  return null;
}

function genObject(depth) {
  if (depth <= 0) return genScalar();
  const keys = range(0, 4);
  const out = {};
  for (let i = 0; i < keys; i++) {
    // Use identifier-shaped keys so the emitter can skip string-quoting them.
    const k = 'k' + i + '_' + range(0, 9);
    out[k] = Math.random() < 0.5 ? genScalar() : genArray(depth - 1);
  }
  return out;
}

function genArray(depth) {
  if (depth <= 0) return [];
  const n = range(0, 5);
  const out = [];
  for (let i = 0; i < n; i++) {
    out.push(Math.random() < 0.5 ? genScalar() : genObject(depth - 1));
  }
  return out;
}

function genSource(literalName, value) {
  // Wrap the serialized value in a plausible-looking source file with
  // prefix and suffix text we later verify is byte-identical after a write.
  const prefix = [
    '// autogenerated test source',
    "import { a } from 'somewhere';",
    "",
    "const OTHER_CONST = 'leave me alone';",
    "",
    "// comment right before the target",
    "const " + literalName + " = ",
  ].join('\n');
  // The initial serialize produces the body.
  const emitted = jsl.serialize(value, { quote: "'", indent: '  ', trailingComma: true });
  const suffix = [
    ';',
    "",
    "function unrelated() { return 42; }",
    "",
    "export default { " + literalName + ", unrelated };",
    "",
  ].join('\n');
  return prefix + emitted + suffix;
}

// ── Property 1a: round-trip preserves every byte outside the literal ──

test('Property 1a: write(source, name, read(source, name).value) preserves surrounding bytes', () => {
  for (let i = 0; i < 100; i++) {
    const name = pick(['FALLBACK_SLIDES', 'DAILY_CONTENT', 'ITEMS', 'MAP_CONFIG']);
    const value = genArray(2);
    const source = genSource(name, value);
    const read1 = jsl.read(source, name);
    assert.ok(read1, 'expected read to find the literal');
    const rewritten = jsl.write(source, name, read1.value);
    // The bytes BEFORE read1.start must equal bytes before in the original.
    const origPrefix = source.slice(0, read1.start);
    const rewrittenPrefix = rewritten.slice(0, read1.start);
    assert.equal(rewrittenPrefix, origPrefix, 'prefix diverged');
    // The bytes AFTER the literal end must equal in both. Since the length
    // might change, we locate the rewritten end by re-reading.
    const read2 = jsl.read(rewritten, name);
    assert.ok(read2, 'expected read of rewritten source to succeed');
    const origSuffix = source.slice(read1.end);
    const rewrittenSuffix = rewritten.slice(read2.end);
    assert.equal(rewrittenSuffix, origSuffix, 'suffix diverged');
  }
});

// ── Property 1b: re-reading after write yields deep-equal value ───────

test('Property 1b: re-read after write returns a value deeply equal to the input', () => {
  for (let i = 0; i < 100; i++) {
    const name = 'MY_LIT_' + i;
    const value = genArray(2);
    const source = genSource(name, value);
    const read1 = jsl.read(source, name);
    const rewritten = jsl.write(source, name, read1.value);
    const read2 = jsl.read(rewritten, name);
    assert.deepEqual(read2.value, read1.value);
  }
});

// ── Example tests ─────────────────────────────────────────────────────

test('read returns null when the named literal is absent', () => {
  const src = "const OTHER = [1, 2, 3];\n";
  assert.equal(jsl.read(src, 'MISSING'), null);
});

test('read accepts unquoted identifier keys, trailing commas, and comments', () => {
  const src = [
    "const CFG = {",
    "  // first key",
    "  key1: 'value1',",
    "  key2: 42, /* trailing comment */",
    "  nested: [1, 2, 3,],",
    "};",
  ].join('\n');
  const got = jsl.read(src, 'CFG');
  assert.deepEqual(got.value, { key1: 'value1', key2: 42, nested: [1, 2, 3] });
});

test('read rejects template-literal interpolation with a typed error', () => {
  const src = "const A = [`hello ${name}`];\n";
  assert.throws(() => jsl.read(src, 'A'), (err) => err.name === 'JsLiteralParseError');
});

test('read rejects regex literals in the value position', () => {
  const src = "const A = [/^foo$/];\n";
  assert.throws(() => jsl.read(src, 'A'), (err) => err.name === 'JsLiteralParseError');
});

test('read rejects spread operators', () => {
  const src = "const A = [...other];\n";
  assert.throws(() => jsl.read(src, 'A'), (err) => err.name === 'JsLiteralParseError');
});

test('read rejects computed keys', () => {
  const src = "const A = { [k]: 1 };\n";
  assert.throws(() => jsl.read(src, 'A'), (err) => err.name === 'JsLiteralParseError');
});

test('write appends to an array and preserves surrounding file text', () => {
  const src = [
    "// head",
    "const ITEMS = [",
    "  { id: 1, label: 'one' },",
    "  { id: 2, label: 'two' },",
    "];",
    "",
    "// tail",
    "",
  ].join('\n');
  const read1 = jsl.read(src, 'ITEMS');
  const newVal = read1.value.concat([{ id: 3, label: 'three' }]);
  const rewritten = jsl.write(src, 'ITEMS', newVal);
  assert.ok(rewritten.startsWith('// head\nconst ITEMS = '));
  assert.ok(rewritten.includes('three'));
  assert.ok(rewritten.endsWith('// tail\n\n'));
  const read2 = jsl.read(rewritten, 'ITEMS');
  assert.equal(read2.value.length, 3);
});
